const codeMirrorThemes = [
  "abcdef",
  "ambiance",
  "ambiance-mobile",
  "base16-dark",
  "base16-light",
  "bespin",
  "blackboard",
  "cobalt",
  "dracula",
  "eclipse",
  "elegant",
  "gruvbox-dark",
  "idea",
  "material",
  "material-darker",
  "material-ocean",
  "material-palenight",
  "monokai",
  "nord",
  "paraiso-dark",
  "paraiso-light",
  "pastel-on-dark",
  "railscasts",
  "rubyblue",
  "shadowfox",
  "solarized",
  "the-matrix",
  "tomorrow-night-bright",
  "tomorrow-night-eighties",
  "xq-light",
  "yeti",
  "zenburn",
];

const codeMirrorKeyBinds = ["default", "vim", "emacs", "sublime"];

module.exports = {
  codeMirrorThemes: codeMirrorThemes,
  codeMirrorKeyBinds: codeMirrorKeyBinds,
};
